### ISSUE TITLE
Mixed Content Error

### ISSUE THREAD

**Issue by ColeDCrawford** [ProjectMirador/mirador-annotot-endpoint-plugin#1]
On [the Netlify demo](https://mirador-annotot-endpoint.netlify.com/), I'm seeing a mixed content error for the [annotation list](http://vatican-dev.sul.stanford.edu/annotations/lists?uri=https%3A%2F%2Fdigi.vatlib.it%2Fiiif%2FMSS_Pal.lat.235%2Fcanvas%2Fp0021), which is being served over HTTP.

**Comment by mejackreed** [comment]
Yep, we are serving that over HTTP :( 

I've setup an open annotot endpoint here for testing/demo https://annotot-app.herokuapp.com/annotations if others want to test with that.
